
services:
  # APPS
  malak:
    build: .
    ports:
      - "8080:8080"
    container_name: malak
    environment:
      INSTANCE: 1


  # Second instance of the app (last name)
  badawy:
    build: .
    ports:
      - "8081:8080"
    container_name: badawy
    environment:
      INSTANCE: 2

  # MongoDB Database
  mongo:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"


  # Mongo Express (Optional GUI)
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9000:8081"

    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
        ME_CONFIG_BASICAUTH: false


  # Nginx Load Balancer
  nginx:
    image: nginx
    ports:
      - "4040:80"
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - malak
      - badawy



